In [2]:
import numpy as np
import pandas as pd
import os, sys, glob
%load_ext autoreload
%autoreload 2
import camcan_utils as utils
import nibabel as nib
from config import *
from nibabel import Nifti1Image
from scipy import stats
from nilearn.maskers import NiftiMasker, NiftiLabelsMasker
import matplotlib.pyplot as plt
import scprep, tphate, phate
from nilearn import plotting
import shutil
import seaborn as sns
from brainiak.searchlight.searchlight import Searchlight
from camcan_utils import get_brain_cmap
import skdim
import ide_helpers as ide

/gpfs/milgram/project/casey/elb77/conda_envs/env_tda/lib/python3.7/site-packages/nilearn/__init__.py:69: FutureWarning: Python 3.7 support is deprecated and will be removed in release 0.12 of Nilearn. Consider switching to Python 3.9 or 3.10.
  _python_deprecation_warnings()

In [5]:
mask = utils.get_intersect_mask(35)
cmap = utils.get_brain_cmap()
# aggregate results
coords = np.where(mask.get_fdata() == 1)
# start with ISC
for t in ['rest','movie','SMT']:
    fns = sorted(glob.glob(f'{CAMCAN_RESULTS_DIR}/ISC/LOSO/*filter_35_{t}*ISC*.nii.gz'))
    print(f'found {len(fns)} for {t} ISC')
    
    # plot the group average
    temp = np.zeros(mask.shape)
    results_vecs = []
    for i, f in enumerate(fns):
        d = nib.load(f).get_fdata()
        temp = np.add(temp, d)
        vec = d[coords[0][:], coords[1][:], coords[2][:]]
        results_vecs.append(vec)
    temp /= len(fns)
    r = np.array(results_vecs)
    print(r.shape)
    np.save(f'{CAMCAN_RESULTS_DIR}/ISC/{t.upper()}_ISC_all_subjects_results.npy', r)
    
    
    n = Nifti1Image(temp, affine=mask.affine)
    nib.save(n, f'{CAMCAN_RESULTS_DIR}/ISC/group_average_{t}_ISC_whole_brain_SL_rad5.nii.gz')
    plot_fn = f'CamCAN/plots/group_average_{t}_ISC_whole_brain_SL_rad5.png'
    plotting.plot_img_on_surf(n, 
                              views=['lateral','medial'], 
                              cmap=cmap, 
                              inflate=True, 
                              bg_on_data=False, 
                                      alpha=0.8,
                              output_file=plot_fn,
                              darkness=0.8, 
                              threshold=0.1,
                              vmax=0.6, title=f'Camcan {t} ISC',
                             )
    plt.close()
    print(plot_fn)

found 117 for rest ISC
(117, 86741)
CamCAN/plots/group_average_rest_ISC_whole_brain_SL_rad5.png
found 117 for movie ISC
(117, 86741)
CamCAN/plots/group_average_movie_ISC_whole_brain_SL_rad5.png
found 117 for SMT ISC
(117, 86741)
CamCAN/plots/group_average_SMT_ISC_whole_brain_SL_rad5.png

In [9]:
for t in ['rest','movie','SMT']:
    for tp in ['optt','autocorr']:
        
        fns = sorted(glob.glob(f'{CAMCAN_RESULTS_DIR}/TPHATE_optt/LOSO/*{t}*{tp}*.nii.gz'))
        print(f'found {len(fns)} for {t} {tp}')

        # plot the group average
        temp = np.zeros(mask.shape)
        results_vecs = []
        for i, f in enumerate(fns):
            d = nib.load(f).get_fdata()
            temp = np.add(temp, d)
            vec = d[coords[0][:], coords[1][:], coords[2][:]]
            results_vecs.append(vec)
        temp /= len(fns)
        r = np.array(results_vecs)
        print(r.shape)
        np.save(f'{CAMCAN_RESULTS_DIR}/TPHATE_optt/{t.upper()}_tphate_{tp}_all_subjects_results.npy', r)


        n = Nifti1Image(temp, affine=mask.affine)
        nib.save(n, f'{CAMCAN_RESULTS_DIR}/TPHATE_optt/group_average_{t}_tphate_{tp}_whole_brain_SL_rad5.nii.gz')
        plot_fn = f'CamCAN/plots/group_average_{t}_tphate_{tp}_whole_brain_SL_rad5.png'
        plotting.plot_img_on_surf(n, 
                                  views=['lateral','medial'], 
                                  cmap=cmap, 
                                  inflate=True, 
                                  bg_on_data=False, 
                                          alpha=0.8,
                                  output_file=plot_fn,
                                  darkness=0.8, 
                                  threshold=1, title=f'Camcan {t} {tp}',
                                 )
        plt.close()
        print(plot_fn)

found 117 for rest optt
(117, 86741)
CamCAN/plots/group_average_rest_tphate_optt_whole_brain_SL_rad5.png
found 117 for rest autocorr
(117, 86741)
CamCAN/plots/group_average_rest_tphate_autocorr_whole_brain_SL_rad5.png
found 117 for movie optt
(117, 86741)
CamCAN/plots/group_average_movie_tphate_optt_whole_brain_SL_rad5.png
found 117 for movie autocorr
(117, 86741)
CamCAN/plots/group_average_movie_tphate_autocorr_whole_brain_SL_rad5.png
found 117 for SMT optt
(117, 86741)
CamCAN/plots/group_average_SMT_tphate_optt_whole_brain_SL_rad5.png
found 117 for SMT autocorr
(117, 86741)
CamCAN/plots/group_average_SMT_tphate_autocorr_whole_brain_SL_rad5.png

In [23]:
# reorganize data

outdir = '/gpfs/milgram/project/casey/elb77/CamCAN/fMRI_organized/'
all_subjects = utils.get_intersecting_subjects(subject_filter=0)

for S in all_subjects:
    s = S.replace('sub-', '')
    dirname = f'{BASE_DIR_CAMCAN}/{CAMCAN_PREPROC_MIDSTR}/{s}/'
    old_fn = glob.glob(os.path.join(dirname, 'Movie', f'*fMR*_{s}*.nii'))[0]
    new_fn = f'{outdir}/movie/{S}_MOVIE.nii'
    shutil.copy(old_fn, new_fn)
    
    old_fn = glob.glob(os.path.join(dirname, 'SMT', f'*fMR*_{s}*.nii'))[0]
    new_fn = f'{outdir}/smt/{S}_SMT.nii'
    shutil.copy(old_fn, new_fn)
    
    old_fn = glob.glob(os.path.join(dirname, 'Rest', f'*fMR*_{s}*.nii'))[0]
    new_fn = f'{outdir}/rest/{S}_REST.nii'
    shutil.copy(old_fn, new_fn)
    print(S)

sub-CC110033
sub-CC110037
sub-CC110045
sub-CC110056
sub-CC110069
sub-CC110087
sub-CC110098
sub-CC110101
sub-CC110126
sub-CC110174
sub-CC110182
sub-CC110187
sub-CC110319
sub-CC110411
sub-CC110606
sub-CC112141
sub-CC120008
sub-CC120049
sub-CC120061
sub-CC120065
sub-CC120120
sub-CC120123
sub-CC120166
sub-CC120182
sub-CC120208
sub-CC120218
sub-CC120234
sub-CC120264
sub-CC120276
sub-CC120286
sub-CC120309
sub-CC120313
sub-CC120319
sub-CC120347
sub-CC120376
sub-CC120409
sub-CC120462
sub-CC120469
sub-CC120470
sub-CC120550
sub-CC120640
sub-CC120727
sub-CC120764
sub-CC120795
sub-CC120816
sub-CC120987
sub-CC121106
sub-CC121111
sub-CC121144
sub-CC121158
sub-CC121194
sub-CC121200
sub-CC121317
sub-CC121397
sub-CC121411
sub-CC121428
sub-CC121479
sub-CC121685
sub-CC121795
sub-CC122172
sub-CC122405
sub-CC122620
sub-CC210023
sub-CC210051
sub-CC210088
sub-CC210124
sub-CC210148
sub-CC210172
sub-CC210182
sub-CC210250
sub-CC210304
sub-CC210314
sub-CC210422
sub-CC210519
sub-CC210526
sub-CC210617
sub-CC210657
sub-CC212153
sub-CC220098
sub-CC220107
sub-CC220115
sub-CC220132
sub-CC220151
sub-CC220198
sub-CC220203
sub-CC220223
sub-CC220232
sub-CC220234
sub-CC220284
sub-CC220323
sub-CC220335
sub-CC220352
sub-CC220372
sub-CC220394
sub-CC220419
sub-CC220506
sub-CC220518
sub-CC220526
sub-CC220535
sub-CC220567
sub-CC220610
sub-CC220635
sub-CC220697
sub-CC220713
sub-CC220806
sub-CC220828
sub-CC220843
sub-CC220901
sub-CC220920
sub-CC220974
sub-CC220999
sub-CC221002
sub-CC221031
sub-CC221033
sub-CC221038
sub-CC221040
sub-CC221054
sub-CC221107
sub-CC221209
sub-CC221220
sub-CC221244
sub-CC221324
sub-CC221336
sub-CC221352
sub-CC221373
sub-CC221487
sub-CC221511
sub-CC221527
sub-CC221565
sub-CC221580
sub-CC221585
sub-CC221595
sub-CC221648
sub-CC221733
sub-CC221740
sub-CC221755
sub-CC221775
sub-CC221828
sub-CC221886
sub-CC221935
sub-CC221954
sub-CC221977
sub-CC221980
sub-CC222120
sub-CC222125
sub-CC222185
sub-CC222258
sub-CC222264
sub-CC222304
sub-CC222326
sub-CC222367
sub-CC222496
sub-CC222555
sub-CC222652
sub-CC222797
sub-CC222956
sub-CC223085
sub-CC223115
sub-CC223286
sub-CC310008
sub-CC310051
sub-CC310052
sub-CC310086
sub-CC310129
sub-CC310135
sub-CC310142
sub-CC310160
sub-CC310203
sub-CC310214
sub-CC310224
sub-CC310252
sub-CC310256
sub-CC310331
sub-CC310361
sub-CC310385
sub-CC310391
sub-CC310397
sub-CC310400
sub-CC310402
sub-CC310407
sub-CC310410
sub-CC310414
sub-CC310450
sub-CC310463
sub-CC310473
sub-CC312058
sub-CC312222
sub-CC320002
sub-CC320022
sub-CC320059
sub-CC320088
sub-CC320089
sub-CC320107
sub-CC320109
sub-CC320160
sub-CC320202
sub-CC320206
sub-CC320218
sub-CC320267
sub-CC320269
sub-CC320297
sub-CC320321
sub-CC320325
sub-CC320336
sub-CC320342
sub-CC320359
sub-CC320379
sub-CC320417
sub-CC320429
sub-CC320448
sub-CC320461
sub-CC320478
sub-CC320500
sub-CC320553
sub-CC320568
sub-CC320574
sub-CC320575
sub-CC320576
sub-CC320608
sub-CC320616
sub-CC320621
sub-CC320636
sub-CC320651
sub-CC320661
sub-CC320680
sub-CC320686
sub-CC320687
sub-CC320698
sub-CC320759
sub-CC320776
sub-CC320814
sub-CC320850
sub-CC320870
sub-CC320888
sub-CC320893
sub-CC320904
sub-CC321000
sub-CC321025
sub-CC321053
sub-CC321069
sub-CC321073
sub-CC321087
sub-CC321107
sub-CC321137
sub-CC321154
sub-CC321174
sub-CC321203
sub-CC321281
sub-CC321291
sub-CC321331
sub-CC321368
sub-CC321428
sub-CC321431
sub-CC321464
sub-CC321504
sub-CC321506
sub-CC321529
sub-CC321544
sub-CC321557
sub-CC321585
sub-CC321594
sub-CC321595
sub-CC321880
sub-CC321899
sub-CC321976
sub-CC322186
sub-CC410015
sub-CC410032
sub-CC410040
sub-CC410084
sub-CC410086
sub-CC410091
sub-CC410094
sub-CC410097
sub-CC410101
sub-CC410113
sub-CC410119
sub-CC410121
sub-CC410169
sub-CC410173
sub-CC410177
sub-CC410179
sub-CC410182
sub-CC410220
sub-CC410222
sub-CC410226
sub-CC410243
sub-CC410248
sub-CC410251
sub-CC410284
sub-CC410287
sub-CC410289
sub-CC410297
sub-CC410323
sub-CC410325
sub-CC410354
sub-CC410387
sub-CC410390
sub-CC410432
sub-CC412004
sub-CC412021
sub-CC420004
sub-CC420060
sub-CC420061
sub-CC420071
sub-CC420075
sub-CC420089
sub-CC420091
sub-CC420094
sub-CC420100
sub-CC420137
sub-CC420143
sub-CC420148
sub-CC420149
sub-CC420157
sub-CC420162
sub-CC420167
sub-CC420173
sub-CC420180
sub-CC420182
sub-CC420197
sub-CC420198
sub-CC420202
sub-CC420204
sub-CC420217
sub-CC420222
sub-CC420226
sub-CC420229
sub-CC420231
sub-CC420236
sub-CC420241
sub-CC420259
sub-CC420260
sub-CC420261
sub-CC420286
sub-CC420322
sub-CC420324
sub-CC420348
sub-CC420356
sub-CC420383
sub-CC420392
sub-CC420396
sub-CC420402
sub-CC420412
sub-CC420433
sub-CC420435
sub-CC420454
sub-CC420462
sub-CC420464
sub-CC420493
sub-CC420566
sub-CC420582
sub-CC420587
sub-CC420589
sub-CC420623
sub-CC420720
sub-CC420729
sub-CC420776
sub-CC420888
sub-CC510015
sub-CC510039
sub-CC510043
sub-CC510050
sub-CC510076
sub-CC510086
sub-CC510115
sub-CC510161
sub-CC510163
sub-CC510208
sub-CC510220
sub-CC510226
sub-CC510237
sub-CC510242
sub-CC510243
sub-CC510255
sub-CC510256
sub-CC510258
sub-CC510259
sub-CC510284
sub-CC510304
sub-CC510321
sub-CC510323
sub-CC510329
sub-CC510342
sub-CC510354
sub-CC510355
sub-CC510392
sub-CC510393
sub-CC510395
sub-CC510415
sub-CC510433
sub-CC510434
sub-CC510438
sub-CC510473
sub-CC510474
sub-CC510480
sub-CC510483
sub-CC510486
sub-CC510534
sub-CC510548
sub-CC510551
sub-CC510568
sub-CC510609
sub-CC510629
sub-CC510639
sub-CC510648
sub-CC512003
sub-CC520002
sub-CC520011
sub-CC520013
sub-CC520042
sub-CC520053
sub-CC520055
sub-CC520065
sub-CC520078
sub-CC520083
sub-CC520097
sub-CC520122
sub-CC520127
sub-CC520134
sub-CC520136
sub-CC520147
sub-CC520168
sub-CC520175
sub-CC520197
sub-CC520200
sub-CC520209
sub-CC520211
sub-CC520215
sub-CC520239
sub-CC520247
sub-CC520253
sub-CC520254
sub-CC520279
sub-CC520287
sub-CC520377
sub-CC520390
sub-CC520391
sub-CC520395
sub-CC520398
sub-CC520424
sub-CC520477
sub-CC520480
sub-CC520503
sub-CC520517
sub-CC520552
sub-CC520560
sub-CC520562
sub-CC520584
sub-CC520585
sub-CC520597
sub-CC520607
sub-CC520624
sub-CC520673
sub-CC520745
sub-CC520775
sub-CC520868
sub-CC520980
sub-CC521040
sub-CC610022
sub-CC610028
sub-CC610039
sub-CC610040
sub-CC610046
sub-CC610051
sub-CC610052
sub-CC610058
sub-CC610061
sub-CC610071
sub-CC610076
sub-CC610099
sub-CC610101
sub-CC610146
sub-CC610178
sub-CC610210
sub-CC610212
sub-CC610227
sub-CC610285
sub-CC610288
sub-CC610292
sub-CC610308
sub-CC610344
sub-CC610372
sub-CC610392
sub-CC610405
sub-CC610469
sub-CC610496
sub-CC610508
sub-CC610568
sub-CC610575
sub-CC610576
sub-CC610594
sub-CC610614
sub-CC610625
sub-CC610631
sub-CC610653
sub-CC610658
sub-CC610671
sub-CC620005
sub-CC620026
sub-CC620044
sub-CC620073
sub-CC620085
sub-CC620090
sub-CC620106
sub-CC620114
sub-CC620118
sub-CC620121
sub-CC620129
sub-CC620152
sub-CC620164
sub-CC620193
sub-CC620259
sub-CC620262
sub-CC620264
sub-CC620279
sub-CC620284
sub-CC620314
sub-CC620354
sub-CC620359
sub-CC620405
sub-CC620406
sub-CC620413
sub-CC620429
sub-CC620436
sub-CC620444
sub-CC620451
sub-CC620454
sub-CC620466
sub-CC620479
sub-CC620490
sub-CC620496
sub-CC620499
sub-CC620515
sub-CC620518
sub-CC620526
sub-CC620549
sub-CC620557
sub-CC620560
sub-CC620567
sub-CC620572
sub-CC620592
sub-CC620610
sub-CC620619
sub-CC620659
sub-CC620685
sub-CC620720
sub-CC620785
sub-CC620793
sub-CC620821
sub-CC620885
sub-CC620919
sub-CC620935
sub-CC621011
sub-CC621080
sub-CC621118
sub-CC621128
sub-CC621184
sub-CC621199
sub-CC621248
sub-CC621284
sub-CC621642
sub-CC710037
sub-CC710088
sub-CC710099
sub-CC710154
sub-CC710176
sub-CC710313
sub-CC710342
sub-CC710350
sub-CC710382
sub-CC710416
sub-CC710429
sub-CC710446
sub-CC710462
sub-CC710486
sub-CC710494
sub-CC710548
sub-CC710551
sub-CC710566
sub-CC710591
sub-CC710664
sub-CC710679
sub-CC710858
sub-CC710982
sub-CC711027
sub-CC711035
sub-CC711128
sub-CC711158
sub-CC711244
sub-CC711245
sub-CC712027
sub-CC720023
sub-CC720071
sub-CC720103
sub-CC720119
sub-CC720180
sub-CC720188
sub-CC720238
sub-CC720290
sub-CC720304
sub-CC720329
sub-CC720358
sub-CC720400
sub-CC720407
sub-CC720497
sub-CC720511
sub-CC720516
sub-CC720622
sub-CC720646
sub-CC720670
sub-CC720685
sub-CC720941
sub-CC720986
sub-CC721052
sub-CC721107
sub-CC721114
sub-CC721224
sub-CC721291
sub-CC721292
sub-CC721374
sub-CC721377
sub-CC721392
sub-CC721418
sub-CC721434
sub-CC721504
sub-CC721519
sub-CC721532
sub-CC721585
sub-CC721618
sub-CC721648
sub-CC721704
sub-CC721707
sub-CC721729
sub-CC721888
sub-CC721891
sub-CC721894
sub-CC722216
sub-CC722421
sub-CC722536
sub-CC722542
sub-CC722651
sub-CC722891
sub-CC723197
sub-CC723395

In [17]:
df_movie = pd.read_csv(CAMCAN_PARTICIPANT_FILES['MOVIE'], sep='\t')
print(df_movie.shape, len(df_movie.participant_id.unique()))
df_movie[df_movie['age']<20]

(649, 6) 649

   participant_id  age   hand gender_text  gender_code  tiv_cubicmm
1    sub-CC110037   18   89.0        MALE            1      1391950
10   sub-CC110182   18   80.0      FEMALE            2      1323662
18   sub-CC120061   19   70.0        MALE            1      1598322
21   sub-CC120123   19   56.0      FEMALE            2      1260867
34   sub-CC120376   18   79.0      FEMALE            2      1236457
35   sub-CC120409   18  100.0        MALE            1      1624266
36   sub-CC120462   18  -80.0      FEMALE            2      1327319
39   sub-CC120550   19   70.0        MALE            1      1471032
47   sub-CC121111   18   90.0        MALE            1      1696915

In [18]:
df_rest = pd.read_csv(CAMCAN_PARTICIPANT_FILES['REST'], sep='\t')
print(df_rest.shape, len(df_rest.participant_id.unique()))
df_rest[df_rest['age']<20]

(652, 6) 652

   participant_id  age   hand gender_text  gender_code  tiv_cubicmm
1    sub-CC110037   18   89.0        MALE            1      1391950
10   sub-CC110182   18   80.0      FEMALE            2      1323662
18   sub-CC120061   19   70.0        MALE            1      1598322
21   sub-CC120123   19   56.0      FEMALE            2      1260867
34   sub-CC120376   18   79.0      FEMALE            2      1236457
35   sub-CC120409   18  100.0        MALE            1      1624266
36   sub-CC120462   18  -80.0      FEMALE            2      1327319
39   sub-CC120550   19   70.0        MALE            1      1471032
47   sub-CC121111   18   90.0        MALE            1      1696915

In [19]:
df_smt = pd.read_csv(CAMCAN_PARTICIPANT_FILES['SMT'], sep='\t')
print(df_smt.shape, len(df_smt.participant_id.unique()))
df_smt[df_smt['age']<20]

(651, 6) 651

   participant_id  age   hand gender_text  gender_code  tiv_cubicmm
1    sub-CC110037   18   89.0        MALE            1      1391950
10   sub-CC110182   18   80.0      FEMALE            2      1323662
18   sub-CC120061   19   70.0        MALE            1      1598322
21   sub-CC120123   19   56.0      FEMALE            2      1260867
34   sub-CC120376   18   79.0      FEMALE            2      1236457
35   sub-CC120409   18  100.0        MALE            1      1624266
36   sub-CC120462   18  -80.0      FEMALE            2      1327319
39   sub-CC120550   19   70.0        MALE            1      1471032
47   sub-CC121111   18   90.0        MALE            1      1696915